spring:
  application:
    name: reactive-orders
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/shopdb
    username: shopuser
    password: shoppass

  datasource:
    url: jdbc:postgresql://localhost:5432/shopdb
    username: shopuser
    password: shoppass
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

  cache:
    type: simple

logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG
    io.r2dbc: DEBUG

management:
    tracing:
      enabled: false
    metrics:
      export:
        otlp:
          enabled: false